name: CRNEngine

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Prepare:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
    - name: Restore tools
      run: dotnet tool restore
    - name: Restore dependencies
      run: dotnet restore CRNEngine/CRNEngineCli.sln
      
  CRN:
    runs-on: windows-2019
    needs: Prepare
    steps:
    - name: Build
      shell: cmd
      run: msbuild CRNEngine/CRNEngineCli.sln /p:Configuration=Release /p:Platform=x64
    - name: Tests 
      run: vstest.console.exe .\CRNEngine\CRNEngineTests\bin\Release\netcoreapp3.1\CRNEngineTests.dll /Platform:x64
